const sqlite3 = require('sqlite3').verbose();
const path = require('path');
const fs = require('fs');

// Determine database path (essential for persistent storage on Render)
const dbPath = process.env.DATABASE_PATH || path.resolve(__dirname, 'verivote.db');

// Ensure directory exists
const dbDir = path.dirname(dbPath);
if (!fs.existsSync(dbDir)) {
  fs.mkdirSync(dbDir, { recursive: true });
}

// Connect to SQLite Database
const db = new sqlite3.Database(dbPath, (err) => {
  if (err) {
    console.error('Error connecting to the database:', err.message);
  } else {
    console.log('Connected to the SQLite database:', dbPath);
  }
});

// Run raw SQL helper
function run(sql, params = []) {
  return new Promise((resolve, reject) => {
    db.run(sql, params, function (err) {
      if (err) {
        reject(err);
      } else {
        resolve({ id: this.lastID, changes: this.changes });
      }
    });
  });
}

// Get single row helper
function get(sql, params = []) {
  return new Promise((resolve, reject) => {
    db.get(sql, params, (err, row) => {
      if (err) {
        reject(err);
      } else {
        resolve(row);
      }
    });
  });
}

// Get multiple rows helper
function all(sql, params = []) {
  return new Promise((resolve, reject) => {
    db.all(sql, params, (err, rows) => {
      if (err) {
        reject(err);
      } else {
        resolve(rows);
      }
    });
  });
}

// Run multiple queries in a transaction
function transaction(queries) {
  return new Promise((resolve, reject) => {
    db.serialize(() => {
      db.run('BEGIN TRANSACTION');
      let index = 0;
      
      const executeNext = () => {
        if (index === queries.length) {
          db.run('COMMIT', (err) => {
            if (err) {
              db.run('ROLLBACK');
              reject(err);
            } else {
              resolve();
            }
          });
          return;
        }

        const { sql, params } = queries[index];
        db.run(sql, params, (err) => {
          if (err) {
            db.run('ROLLBACK');
            reject(err);
          } else {
            index++;
            executeNext();
          }
        });
      };

      executeNext();
    });
  });
}

const crypto = require('crypto');

function hashPassword(password) {
  return crypto.createHash('sha256').update(password).digest('hex');
}

// Initialize tables
async function initDatabase() {
  try {
    // Enable Foreign Keys in SQLite
    await run("PRAGMA foreign_keys = ON");

    // 1. Admin Invitation Codes (Generated by Super Admin)
    await run(`
      CREATE TABLE IF NOT EXISTS admin_codes (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        code TEXT UNIQUE NOT NULL,
        used INTEGER DEFAULT 0,          -- 0 = Unused, 1 = Used
        used_by TEXT,                    -- Admin name
        used_for_school TEXT,            -- School name
        created_at INTEGER NOT NULL
      )
    `);

    // 2. School Administrators
    await run(`
      CREATE TABLE IF NOT EXISTS school_admins (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        school TEXT NOT NULL,
        password TEXT NOT NULL,
        invite_code TEXT UNIQUE NOT NULL,
        created_at INTEGER NOT NULL,
        FOREIGN KEY(invite_code) REFERENCES admin_codes(code) ON DELETE CASCADE
      )
    `);

    // Database Migration: Add password column if it's missing from older schema
    try {
      await run("ALTER TABLE school_admins ADD COLUMN password TEXT");
      await run("UPDATE school_admins SET password = ? WHERE password IS NULL", [hashPassword('admin')]);
    } catch (err) {
      // Column already exists
    }

    // 3. Elections Table (Scoped to a School)
    await run(`
      CREATE TABLE IF NOT EXISTS elections (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        school TEXT NOT NULL,
        title TEXT NOT NULL,
        institution TEXT NOT NULL,
        scope TEXT NOT NULL, -- 'School-Wide', 'Faculty', 'Department'
        scope_name TEXT,     -- e.g., 'Engineering' or 'Computer Science'
        start_time INTEGER NOT NULL,
        end_time INTEGER NOT NULL,
        status TEXT DEFAULT 'active',
        created_by TEXT      -- admin name who launched this election
      )
    `);

    // Migration: Add created_by column to elections if missing
    try {
      await run("ALTER TABLE elections ADD COLUMN created_by TEXT");
    } catch (err) {
      // Column already exists
    }

    // 4. Candidates Table (Linked to Election)
    await run(`
      CREATE TABLE IF NOT EXISTS candidates (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        election_id INTEGER,
        name TEXT NOT NULL,
        role TEXT NOT NULL, -- e.g., 'President', 'Treasurer'
        bio TEXT,
        image_data TEXT,    -- Base64 photo or placeholder name
        votes INTEGER DEFAULT 0,
        FOREIGN KEY(election_id) REFERENCES elections(id) ON DELETE CASCADE
      )
    `);

    // 5. Voter IDs Table (Linked to Election)
    await run(`
      CREATE TABLE IF NOT EXISTS voter_ids (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        election_id INTEGER,
        voter_code TEXT UNIQUE NOT NULL,
        voted INTEGER DEFAULT 0,         -- 0 = False, 1 = True
        voted_at INTEGER,
        matric_number TEXT,
        student_name TEXT,
        FOREIGN KEY(election_id) REFERENCES elections(id) ON DELETE CASCADE
      )
    `);

    // Migration: Add matric_number and student_name columns if missing from older schema
    try {
      await run("ALTER TABLE voter_ids ADD COLUMN matric_number TEXT");
    } catch (err) {
      // Column already exists
    }
    try {
      await run("ALTER TABLE voter_ids ADD COLUMN student_name TEXT");
    } catch (err) {
      // Column already exists
    }

    // 6. Dynamic Positions Table (Scoped to School)
    await run(`
      CREATE TABLE IF NOT EXISTS positions (
        name TEXT NOT NULL,
        school TEXT NOT NULL,
        created_by TEXT,
        PRIMARY KEY (name, school)
      )
    `);

    // Migration: Add created_by column to positions if missing
    try {
      await run("ALTER TABLE positions ADD COLUMN created_by TEXT");
    } catch (err) {
      // Column already exists
    }

    // 7. Global Candidate Registry Table (Scoped to School)
    await run(`
      CREATE TABLE IF NOT EXISTS candidate_registry (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        role TEXT NOT NULL,
        school TEXT NOT NULL,
        bio TEXT,
        image_data TEXT,
        created_by TEXT,
        FOREIGN KEY(role, school) REFERENCES positions(name, school) ON DELETE CASCADE
      )
    `);

    // Migration: Add created_by column to candidate_registry if missing
    try {
      await run("ALTER TABLE candidate_registry ADD COLUMN created_by TEXT");
    } catch (err) {
      // Column already exists
    }

    // 8. Pre-Approved Registered Schools Table
    await run(`
      CREATE TABLE IF NOT EXISTS registered_schools (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT UNIQUE NOT NULL,
        created_at INTEGER NOT NULL
      )
    `);

    // --- ONE-TIME DATA MIGRATION: MERGE '0AU' INTO 'OAU' ---
    const hasZeroAU = await get("SELECT school FROM school_admins WHERE school = '0AU' LIMIT 1");
    if (hasZeroAU) {
      console.log("Migration: Merging '0AU' data into 'OAU'...");
      await run("PRAGMA foreign_keys = OFF");
      await run("UPDATE school_admins SET school = 'OAU' WHERE school = '0AU'");
      await run("UPDATE admin_codes SET used_for_school = 'OAU' WHERE used_for_school = '0AU'");
      await run("UPDATE elections SET school = 'OAU', institution = 'OAU' WHERE school = '0AU'");
      await run("UPDATE candidate_registry SET school = 'OAU' WHERE school = '0AU'");
      await run("INSERT OR IGNORE INTO positions (name, school) SELECT name, 'OAU' FROM positions WHERE school = '0AU'");
      await run("DELETE FROM positions WHERE school = '0AU'");
      await run("PRAGMA foreign_keys = ON");
      console.log("Migration: '0AU' data successfully merged into 'OAU'.");
    }

    // --- SEED DEFAULT CODES AND DEMO SCHOOL ADMINS ---
    
    // Seed default Super Admin generated code if none exists
    const testCode = await get("SELECT code FROM admin_codes WHERE code = 'VV-INV-DEMO'");
    if (!testCode) {
      const now = Date.now();
      await run(
        "INSERT INTO admin_codes (code, used, used_by, used_for_school, created_at) VALUES (?, ?, ?, ?, ?)",
        ['VV-INV-DEMO', 1, 'Dean Engineering', 'Veritas University', now]
      );
      
      // Seed default school administrator
      await run(
        "INSERT INTO school_admins (name, school, password, invite_code, created_at) VALUES (?, ?, ?, ?, ?)",
        ['Dean Engineering', 'Veritas University', hashPassword('admin'), 'VV-INV-DEMO', now]
      );
      
      // Seed default positions for Veritas University
      await run("INSERT INTO positions (name, school, created_by) VALUES ('President', 'Veritas University', 'Dean Engineering')");
      await run("INSERT INTO positions (name, school, created_by) VALUES ('Secretary', 'Veritas University', 'Dean Engineering')");
      
      console.log('Seeded Veritas University demo school admin, invite code, and positions.');
    }



    // Seed default pre-approved schools
    const nowTime = Date.now();
    await run("INSERT OR IGNORE INTO registered_schools (name, created_at) VALUES ('Veritas University', ?)", [nowTime]);
    await run("INSERT OR IGNORE INTO registered_schools (name, created_at) VALUES ('OAU', ?)", [nowTime]);

    // Seed OAU admins if they don't exist
    const oauAdmins = [
      { name: 'EMI SWAN', school: 'OAU', password: 'admin', code: 'VV-INV-JT2S8' },
      { name: 'PMARX', school: 'OAU', password: '3321', code: 'VV-INV-BDFZH' },
      { name: 'IFMSA adm', school: 'OAU', password: '1234', code: 'VV-INV-BKMLC' }
    ];

    for (const admin of oauAdmins) {
      const existing = await get("SELECT name FROM school_admins WHERE name = ? COLLATE NOCASE", [admin.name]);
      if (!existing) {
        const now = Date.now();
        // Seed code
        await run(
          "INSERT OR IGNORE INTO admin_codes (code, used, used_by, used_for_school, created_at) VALUES (?, ?, ?, ?, ?)",
          [admin.code, 1, admin.name, admin.school, now]
        );
        // Seed admin
        await run(
          "INSERT OR IGNORE INTO school_admins (name, school, password, invite_code, created_at) VALUES (?, ?, ?, ?, ?)",
          [admin.name, admin.school, hashPassword(admin.password), admin.code, now]
        );
        // Seed default positions for OAU
        await run("INSERT OR IGNORE INTO positions (name, school, created_by) VALUES ('President', 'OAU', ?)", [admin.name]);
        await run("INSERT OR IGNORE INTO positions (name, school, created_by) VALUES ('Secretary', 'OAU', ?)", [admin.name]);
        
        console.log(`Seeded administrator: ${admin.name} for school: ${admin.school}`);
      }
    }

    console.log('Database tables initialized successfully.');
  } catch (error) {
    console.error('Failed to initialize database tables:', error);
  }
}

module.exports = {
  db,
  run,
  get,
  all,
  transaction,
  initDatabase,
  hashPassword
};
